server:
  port: 9004

spring:
  application:
    name: xdclass-order-service
  redis:
    host: 192.1.1.101
    password: 123456
    port: 8000
  cloud:
    #注册中心地址
    nacos:
      discovery:
        server-addr: 192.1.1.101:8848

  rabbitmq:
    host: 192.1.1.101
    port: 5672
    virtual-host: /dev
    password: password
    username: admin

    #消息手工确认ACK
    listener:
      simple:
        acknowledge-mode: manual
  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/xdclass_order?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123123

#配置plus打印sql日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


#设置日志级别,ERROR/WARN/INFO/DEBUG,默认是INFO以上才显示
logging:
  level:
    root: INFO